config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, only: []
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registratinons: 'companies/registrations'
  }
  
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registratinons: 'students/registrations'
  }
  
  resources :students, only: [:index, :show, :edit, :update]
  resources :companies, only: [:show, :edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :scrooms, only: [:index, :show, :create] 
  resources :scmessages, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  has_attached_file :avatar, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png"]      

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :scrooms


  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    family_name? && family_name_kana? && first_name? && first_name_kana? && avatar?
  end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @company = Company.find(search_id)
    end

    def show
        @student = Student.find(params[:id])
        @currentStudentEntry = Entry.where(student_id: current_student.id)
        @studentEntry = Entry.where(student_id: @student.id)

        if @student.id == current_student.id #表示しているのが自分のページの場合
        else
            #表示している学生と自分のエントリに共通のroom_idがあるかどうか検索
            @currentStudentEntry.each do |cs|
                @studentEntry.each do |s|
                    if cs.room_id == s.room_id then
                        @isRoom = true
                        @roomId = cs.room_id
                    end
                end
            end
            #共通のRoomがなければ作る
            if @isRoom
            else
                @room = Room.new
                @entry = Entry.new
            end
        end
    end

    def edit
    end

    def update
        current_student.update(update_params)
    end


    private
    def update_params
        params.require(:student).permit(:family_name, :family_name_kana, :first_name, :first_name_kana, :avatar)
    end

    def search_id
        if params.permitted?
            params.require(:company).permit(:id)
        else
            1
        end
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_student do |f| %>
    <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<% unless current_student.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
    <%= link_to 'プロフィールを登録する', edit_student_path(current_student), {class: 'btn btn-lg btn-primary withripple' } %>
  </header>
<% else %>
  <div class="card_wrapper">
    <%= render partial: "cards/card",:locals => {company: @company} %>
    <div class="btn-wrapper">
      <%= link_to "○", company_path(@company), {class: "btn btn-design-a" } %>
      <%= button_to "x", {action: 'index', :id => @company.id+1}, :method => :get,  :class => "btn btn-design-b" %>
      <%# <%= form_tag(students_path, :method => :get)do %>
        <%# <%= hidden_field :id, "#{@company.id}+1" %> 
        <%# <%= submit_tag "×", :class => "btn btn-primary withripple btn-design-b " %> 
      <%# <% end %> 
    </div>
  <div>
<% end %>

app/views/students/show.html.erb
<div class="row form user_profile">
    <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= @student.avatar.url(:medium) %>);"></div>
        <h2><%= "#{@student.name}" %><span><%= "#{@student.name_kana}"%></span></h2>
        <% if current_student.id == @student.id %>
            <div class="profile_edit">
                <%= link_to 'プロフィール編集', edit_student_path(current_student), {:class => 'btn btn-primary withripple'} %>
            </div>
        <% else %>
            <% if @isRoom == true %>
                <div class="btn btn-primary withripple"><a href="/rooms/<%= @roomId %>">チャットへ</a>
            <% else %>
                <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e|%>
                        <%= e.hidden_field :student_id, :value=> @student.id%>
                    <% end %>
                <%= f.submit "チャットを始める" %>
            <% end %>
        <% end %>
    <% end %>
    </div>
  </div>

app/views/students/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>