config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, only: []
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registratinons: 'companies/registrations'
  }
  
  devise_for :students, controllers: {
    sessions: 'students/sessions',
    passwords: 'students/passwords',
    registratinons: 'students/registrations'
  }
  
  resources :students, only: [:index, :show, :edit, :update]
  resources :companies, only: [:show, :edit, :update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :scrooms, only: [:index, :show, :create] 
  resources :scmessages, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "top#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type:["image/jpg", "image/jpeg", "image/png"]

  has_many :scrooms

  def send_message(student, room_id, content)
    from_messages.create!(to_id: student.id, room_id: room_id, content: content)
  end

  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"    
  end

end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :student
    belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :student
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/scmessage.rb
class Scmessage < ApplicationRecord
end

app/models/scroom.rb
class Scroom < ApplicationRecord
  belongs_to :student
  belongs_to :company
  has_many :scmessages
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  has_attached_file :avatar, styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg", "image/jpeg", "image/png"]      

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :scrooms


  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    family_name? && family_name_kana? && first_name? && first_name_kana? && avatar?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def create 
        @room = Room.create #新規Roomテーブルを作成
        @entry1 = Entry.create(:room_id => @room.id, :student_id => current_student.id) #新規Entryを作成
        @entry2 = Entry.create(params.require(:entry).permit(:student_id, :room_id).merge(:room_id => @room.id))
        redirect_to "/rooms/#{@room.id}"
    end

    def show
        @room = Room.find(params[:id])
        if Entry.where(:student_id => current_student.id, :room_id => @room.id).present?
            @messages = @room.messages
            @message = Message.new
            @entries = @room.entries
        else
            redirect_back(fallback_locaktion: root_path)
        end
    end
end

app/controllers/scrooms_controller.rb
class ScroomsController < ApplicationController
    def index
        if student_signed_in?
            @currentScrooms = Scroom.where("student_id = ?",current_student.id)
        elsif company_signed_in?
            @currentScrooms = Scroom.where("company_id = ?",current_company.id)
        end
    end

    def show
        @scroom = Scroom.find(params[:id]) #ルーム情報取得
        @scmessage = Scmessage.new #新規メッセージ投稿
        @scmessages = @scroom.scmessages #このルームのメッセージをすべて取得
        if student_signed_in?
            if @scroom.student.id == current_student.id
                @company = @scroom.company
            else
                redirect_to "students_path"
            end
        elsif company_signed_in?
            if @scroom.company.id == current_company.id
                @student = @scroom.student
            else
                redirect_to "company_path(current_company.id)"
            end
        else
            redirect_to "/"
        end
    end

    def create
        if student_signed_in?
            @scroom = Scroom.new(scroom_params)
        elsif company_signed_in?
            @scroom = Scroom.new(scroom_student_params)
            @scroom.company_id  = current_company.id
        else
            redirect_to "/"
        end
        if @scroom.save
            redirect_to "/scrooms/#{@scroom.id}"
        else
            redirect_to "/"
        end
    end

    private
    def scroom_params
        params.require(:scroom).permit(:student_id, :company_id, :scroom_id)
    end
    def scroom_company_params
        params.require(:scroom).permit(:company_id)
    end

    def scroom_student_params
        params.require(:scroom).permit(:student_id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    layout "index"
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/scmessages_helper.rb
module ScmessagesHelper
end

app/helpers/scrooms_helper.rb
module ScroomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<div class="card">
        <div class="card-image " style="background-image: url(<%= @company.avatar.url(:medium) %>)"></div>
        <div class="question_user_info card-info">
            <%= link_to company.name, company_path(company)%>
        </div>

</div>

app/views/cards/_end.html.erb
<div class="question_content top_content">
    <header class="question_header">
        <div class="question_user_info user_info">
            <span>今日はもうおしまいです。また明日きてね。</span>
        </div>
    </header>
</div>

app/views/common/_header.html.erb
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
         </script>
<% if student_signed_in?||company_signed_in? %>
  <div class='navbar navbar-default navbar-fixed-top'>
    <div class='container'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag 'logo_1.png' %> <small class='hidden-xs hidden-sm'>地方と都会をつなぐ新しい出会いを。</small>
      <% end %>
      <% if student_signed_in? %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', students_path %></li>
              <li><%= link_to 'マイページ', student_path(current_student)%></li>
              <li><%= link_to 'プロフィール編集', edit_student_path(current_student)%></li>
              <li><%= link_to 'チャットルーム一覧', scrooms_path %></li>
              <li><%= link_to 'ログアウト', destroy_student_session_path, method: :delete %></li>
        </ul>
      </div>
      <% elsif company_signed_in? %>
      <div class='navbar-collapse collapse navbar-responsive-collapse navbar-right'>
        <ul class='nav navbar-nav'>
          <li><%= link_to 'HOME', company_path(current_company) %></li>
              <li><%= link_to 'マイページ', company_path(current_company)%></li>
              <li><%= link_to 'プロフィール編集', edit_company_path(current_company)%></li>
              <li><%= link_to 'チャットルーム一覧', scrooms_path %></li>
              <li><%= link_to 'ログアウト', destroy_company_session_path, method: :delete %></li>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>

app/views/common/_login_logo.html.erb
<div class='sign_up_logo'>
  <%= image_tag 'logo_1.png' %>
  <small>地方にない、新しい出会いを。</small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta cherset="utf-8">
    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <meta viewport content='width=devise-width, initial-scale=1.0'>
    <title>empower</title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render partial: 'common/header' %>
          <%= bootstrap_flash %>
          <%= yield %>
      <footer class='row text-center'>
        <p>(C) empower 2019</p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta cherset="utf-8">
    <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
    <meta name="viewport" content="width=devise-width, initial-scale=1.0,user-scalable=no">
    <title>empower</title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= stylesheet_link_tag    'top/top.css', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body id="top">
<header class="topPage">
    <div class="bg-mask">
        <h1>empower
            <p>地方学生に、「縁」という力を。</p>
        </h1>
        <nav>
            <ul>
                <li><%= link_to "企業の皆様へ", new_company_session_path %></a></li>
                <li><%= link_to "ログイン", new_student_session_path %></li>
            </ul>
        </nav>
    </div>
</header>

<aside class="note">
    <ul>
        <li><span class="date">2019.05.07</span><a href="#">サイトをプレオープンしました</a></li>
    </ul>
</aside>

<section class="info">
    <ul>
        <li><%= link_to "学生会員登録", new_student_registration_path %></li>
    </ul>
    <p class="annotation">empowerをご利用いただくには、会員登録が必要です。</p>
</section>

<section class="main">
    <section class="aboutTop">
        <div>
            <h2>empowerとは</h2>
            <p>empowerは地方の学生に出会いを提供するサービスです。<br>「出会いは、人生を変える。」<br>新しい視点をくれる出会いを通じてこれまでにないワクワク、そして力を手に入れよう。</p>
        </div>
    </section>
</section>

<footer class='row text-center'>
    <p>(C) empower 2019</p>
</footer>
        
  </body>
</html>